name: Changeset Version

on:
  push:
    branches: [main]
    paths-ignore: ["README.md"]

jobs:
  version:
    runs-on: ubuntu-latest
    # For all pushes to main that do not have a commit message that starts with Version Packages, and thus aren't merging a versioning PR
    # Run the changesets action, which will either no-op if there are no changesets present,
    # or generate the Version Packages PR containing the updated version and merged release notes if there are changesets present
    if: ${{ !startsWith(github.event.commits[0].message, 'Version Packages') }}
    steps:
      - name: checkout
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0
          persist-credentials: false # Fixes issue identified in https://github.com/changesets/action/issues/70

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.9.5

      - name: setup node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: "14.*"
          cache: "pnpm"

      # Why do we explicitly do pnpm install here and not use "run_install: true" above in the pnpm setup?
      # We need to have pnpm setup before node in order to take advantage of the inbuilt caching that is available
      # in that action, and running an install as part of pnpm setup won't use the cache, so we'll explicitly
      # run it here after the cache
      - run: pnpm install

      - uses: changesets/action@v1.4.1
        with:
          version: pnpm run ci:version
        env:
          GITHUB_TOKEN: ${{ secrets.CHANGESETS_GITHUB_TOKEN }}
